services:
  ait-server:
    container_name: ait-server
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on: [tcp-server-send, tcp-server, udp-server]
    command: ["source ~/.bashrc && ait-server"]
    environment:
      LOG_LEVEL: INFO
    networks:
      - ait

  # tcp-client:
  #   container_name: tcp-client
  #   platform: linux/amd64
  #   build:
  #     context: ../
  #     dockerfile: ./docker/Dockerfile
  #   depends_on: [ait-server]
  #   command: ["source /home/ait/.bashrc && cd AIT-Core && workon ait && python scripts/network_tester.py client TCP ait-server 1234"]
  #   networks:
  #     - ait

  udp-client-1:
    container_name: udp-client-1
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on: [ait-server]
    command: ["source ~/.bashrc && python scripts/network_tester.py client UDP ait-server 1234"]
    networks:
      - ait

  tcp-client-2:
    container_name: tcp-client-2
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on: [ait-server]
    command: ["source ~/.bashrc && python scripts/network_tester.py client TCP ait-server 1235"]
    networks:
      - ait

  # udp-client-2:
  #   container_name: udp-client-2
  #   platform: linux/amd64
  #   build:
  #     context: ../
  #     dockerfile: ./docker/Dockerfile
  #   depends_on: [ait-server]
  #   command: ["source ~/.bashrc && python scripts/network_tester.py client UDP ait-server 1235"]
  #   networks:
  #     - ait

  tcp-server:
    container_name: tcp-server
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: ["source ~/.bashrc && python -u scripts/network_tester.py server TCP 0.0.0.0 1237"]
    networks:
      - ait

  tcp-server-send:
    container_name: tcp-server-send
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: ["source ~/.bashrc && python scripts/network_tester.py server TCP-SEND 0.0.0.0 1236"]
    networks:
      - ait

  udp-server:
    container_name: udp-server
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: ["source ~/.bashrc && python -u scripts/network_tester.py server UDP 0.0.0.0 1238"]
    networks:
      - ait

networks:
  ait:
    name: ait