- !Command
  name:      NO_OP
  opcode:    0x0001
  subsystem: CORE
  title: NO_OP
  desc:      |
    Standard NO_OP command.

- !Command
  name:      SEQ_START
  opcode:    0x0002
  subsystem: CMD
  title: Start Sequence
  desc:      |
    This command starts a specified command sequence.

  arguments:
    - !Argument
      name:  sequence_id
      desc:  Sequence ID
      units: none
      type:  MSB_U16
      bytes: [0,1]

- !Command
  name:      SEQ_ENABLE_DISABLE
  opcode:    0x0003
  subsystem: CMD
  title: Enable/Disable Sequence
  desc:      |
    This command enables or disabled the specified sequence.  If a
    sequence to be disabled is currently executing, it will be
    interrupted.

  arguments:
    - !Argument
      name:  sequence_id
      desc:  Sequence ID
      units: none
      type:  MSB_U16
      bytes: [0,1]

    - !Argument
      name:  enable
      desc:  Enable
      units: none
      type:  U8
      bytes: 2
      enum:
        0: DISABLED
        1: ENABLED

- !Command
  name:      SEND_FIXED_ARG
  opcode:    0x0004
  subsystem: CMD
  title: Send Fixed Argument
  desc:      |
    This command tests sending a fixed argument.

  arguments:
    - !Fixed
      name: fixed_arg
      desc: Fixed Argument
      units: none
      type: MSB_U16
      bytes: [0,1]
      value: 5

- !Command
  name:      SEND_STR_ARG
  opcode:    0x0005
  subsystem: CMD
  title: Send string argument value
  desc:      |
    This command tests sending a single string argument.

  arguments:
    - !Argument
      name: str_arg
      desc: String Argument
      units: none
      type: S16
      bytes: [0,15]

# below is example of including additional command dictionary file
# - !include core_set_op_mode.yaml
