#!/usr/bin/env python

"""
BLISS Telemetry Defintions to TeX

Outputs BLISS Telemetry Definitions in TeX format.
"""

"""
Authors: Ben Bornstein

Copyright 2016 California Institute of Technology.  ALL RIGHTS RESERVED.
U.S. Government Sponsorship acknowledged.
"""


from bliss.core import tlm

Packet = 'OCO3_1553_EHS'

def sanitize (s):
  """Returns a santized string with special TeX characters escaped."""
  if s is None:
    return s

  s = s.replace('&', '\&')
  s = s.replace('<', '{\\textless}')
  s = s.replace('>', '{\\textgreater}')
  s = s.replace('^', '{\\textasciicircum}')
  return s


filename = 'tlmdict-07-tlmdefs.tex'
output   = open(filename, 'wt')
d        = tlm.getDefaultDict()

n = 0
output.write('\\begin{tlmdetails}\n')

for defn in d[Packet].fields[18:]:
#    if n == 10:
#        output.write('\\end{tlmdetails}\n')
#        output.write('\\begin{tlmdetails}\n')
#        n = 0

    if type(defn.bytes) is list:
      start = defn.bytes[0]
    else:
      start = defn.bytes
    values = (start, defn.name, sanitize(defn.desc), defn.type.name)
    output.write('%d & \\tlmarg{%s} & %s & %s\\\\\n' % values)
    output.write('  \\hline\n')

    n = n + 1

output.write('\\end{tlmdetails}\n')
output.write('\n')
output.close()
